# This workflow will run lint and many other pre-commit hooks
# https://pre-commit.com/

name: pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Pre-commit checks
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        pip install pre-commit
        pre-commit install
    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files
